#!/usr/bin/bash
# pakman-install, version 0
#
# installs and/or removes packages using pacman and runs pacdiff afterwards if necessary
# Copyright (C) 2014 Thomas Binkau
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


ROOT_UID=0
E_NOTROOT=78
INSTALL=""
DEINSTALL=""

# Make sure only root can run this script
if [ "$EUID" -ne "$ROOT_UID" ]
then
  echo "Must be root to run this script" 1>&2
  exit $E_NOTROOT
fi

# Run update
if [ "$#" -ge "2" ]
then
  if [ "$1" = "-i" ]
  then
    INSTALL="$2"
    if [ "$#" -eq "4" ]
    then
      if [ "$3" = "-r" ]
      then
	DEINSTALL="$4"
      else
	echo "usage: pakman-install [-i \"pkg1 pkg...\"] [-r \"pkg2 pkg...\""]
	echo "       packages after -i will be installed, after -r removed."
	exit 0
      fi
    else
      if [ "$#" -ne "2" ]
      then
	echo "usage: pakman-install [-i \"pkg1 pkg...\"] [-r \"pkg2 pkg...\""]
	echo "       packages after -i will be installed, after -r removed."
	exit 0
      fi
    fi
  else
    if [ "$1" = "-r" ] && [ "$#" -eq "2" ]
    then
      DEINSTALL="$2"
    else
      echo "usage: pakman-install [-i \"pkg1 pkg...\"] [-r \"pkg2 pkg...\""]
      echo "       packages after -i will be installed, after -r removed."
      exit 0
    fi
  fi
else
   echo "usage: pakman-install [-i \"pkg1 pkg...\"] [-r \"pkg2 pkg...\""]
   echo "       packages after -i will be installed, after -r removed."
   exit 0
fi

# install
if [ -n "$INSTALL" ]
then
  echo -e "\e[0;32m[install]\e[0m"
  echo "/bin/pacman -S "$INSTALL
  /bin/pacman -S $INSTALL
  echo
fi

# remove
if [ -n "$DEINSTALL" ]
then
  echo -e "\e[0;31m[remove]\e[0m"
  echo "/bin/pacman -Rsc "$DEINSTALL
  /bin/pacman -Rsc $DEINSTALL
  echo
fi

if [ -n "$INSTALL" ]
then
  echo "root: pacdiff"
  #export LANG=C; export LC_ALL=C
  #export DIFFPROG=meld
  export DIFFSEARCHPATH="/boot /etc /usr"
  /bin/pacdiff
  echo
fi
read -N 1 -p "finished. press any key to close"
