#!/usr/bin/bash
# system-update, version 1
#
# runs a full system update using pacman and pacdiff afterwards
# Copyright (C) 2014 Thomas Binkau
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


ROOT_UID=0
E_NOTROOT=78

# Make sure only root can run this script
if [ "$EUID" -ne "$ROOT_UID" ]
then
   echo "Must be root to run this script" 1>&2
   exit $E_NOTROOT
fi

# Run update
if [ "$#" -eq "1" ] && [ "$1" = "-u" ]
then
   echo "root: pacman -Su"
   /bin/pacman -Su
else
   echo "root: pacman -Syu"
   /bin/pacman -Syu
fi
echo

# Run pacdiff
echo "root: pacdiff"
#export LANG=C; export LC_ALL=C
#export DIFFPROG=meld
export DIFFSEARCHPATH="/boot /etc /usr"
/bin/pacdiff
echo

# Wait for input
read -N 1 -p "finished. press any key to close"
